'use client';
import {useState} from 'react';
import {ClassRsvp,CreateMeetup} from './MeetupControls';
import styles from './class-meetups.module.css';
type Meetup={id:string;title:string;blurb:string|null;location_name:string;starts_at:string;creator_id:string;joined:boolean;attendeeCount:number};
const date=(value:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',...options}).format(new Date(value));
export default function MeetupAgenda({spaceId,subspaceId,userId,meetups}:{spaceId:string;subspaceId:string;userId:string;meetups:Meetup[]}){
 const [filter,setFilter]=useState<'all'|'going'|'hosting'>('all');
 const shown=meetups.filter(m=>filter==='all'||(filter==='going'?m.joined:m.creator_id===userId));
 return <section className={styles.screen} aria-label="Class meetups"><header className={styles.header}><div><h1>Meetups</h1><p>Make time to study together.</p></div><CreateMeetup spaceId={spaceId} subspaceId={subspaceId}/></header>
 <div className={styles.toolbar}><div className={styles.filters} aria-label="Filter meetups">{([{id:'all',label:'Upcoming'},{id:'going',label:'Going'},{id:'hosting',label:'Hosting'}] as const).map(f=><button key={f.id} aria-pressed={filter===f.id} onClick={()=>setFilter(f.id)}>{f.label}</button>)}</div><span className={styles.zone}>Pacific time</span></div>
 {!shown.length?<div className={styles.empty}><span className={styles.emptyIcon} aria-hidden="true"><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-9 4v3m-2-1.5h4"/></svg></span><h2>{filter==='all'?'Your next study session starts here':filter==='going'?'Nothing on your calendar yet':'Bring your class together'}</h2><p>{filter==='all'?'Create a meetup and give your classmates a place to join you.':filter==='going'?'Join an upcoming meetup and you’ll find it here.':'Sessions you create will appear here.'}</p>{filter==='going'&&<button className={styles.textButton} onClick={()=>setFilter('all')}>Explore upcoming sessions</button>}</div>:<ul className={styles.feed}>{shown.map((m,i)=>{const month=date(m.starts_at,{month:'long',year:'numeric'}),previous=i?date(shown[i-1].starts_at,{month:'long',year:'numeric'}):null;return <li key={m.id}>{month!==previous&&<h2 className={styles.month}>{month}</h2>}<article className={styles.card}>
 <div className={styles.dateTile} aria-hidden="true"><span>{date(m.starts_at,{weekday:'short'})}</span><strong>{date(m.starts_at,{day:'2-digit'})}</strong><small>{date(m.starts_at,{month:'short'})}</small></div>
 <div className={styles.details}><div className={styles.cardHeading}><time dateTime={m.starts_at}>{date(m.starts_at,{weekday:'long',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time>{m.joined&&m.creator_id!==userId&&<span className={styles.going}>Going</span>}</div><h3>{m.title}</h3><p className={styles.location}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg><span>{m.location_name}</span></p>{m.blurb&&<p className={styles.blurb}>{m.blurb}</p>}<footer className={styles.cardFooter}><span className={styles.attendance}>{m.attendeeCount} {m.attendeeCount===1?'person':'people'} going</span><ClassRsvp spaceId={spaceId} subspaceId={subspaceId} meetupId={m.id} joined={m.joined} hosting={m.creator_id===userId}/></footer></div>
 </article></li>;})}</ul>}{meetups.length===100&&<p className={styles.hint}>Showing the next 100 sessions.</p>}
 </section>;
}
