import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
test('DM participants only, unread counts and member directory privacy',async()=>{const db=new PGlite();const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',c='00000000-0000-0000-0000-000000000003';try{
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create function auth.uid() returns uuid language sql stable as $$select current_setting('request.jwt.claim.sub')::uuid$$;grant usage on schema auth to authenticated;
create table profiles(id uuid primary key,name text,major text,avatar_url text);create table subspaces(id text primary key,space_id text,professor_id text);create table spaces(id text,course_id text);create table sections(id text,course_id text,professor_id text);create table enrollments(user_id uuid,section_id text);
create function public.is_subspace_member(text) returns boolean language sql stable as $$select current_setting('test.member',true)='yes'$$;
insert into profiles values('${a}','Alice',null,null),('${b}','Bob',null,null),('${c}','Chris',null,null);
insert into subspaces values('class','space','prof');insert into spaces values('space','course');insert into sections values('section','course','prof');insert into enrollments values('${a}','section'),('${b}','section'),('${c}','section');`);
await db.exec(await readFile('supabase/migrations/202609050014_classmates_dm.sql','utf8'));
await db.exec(`insert into class_direct_messages(id,subspace_id,sender_id,recipient_id,body) values(gen_random_uuid(),'class','${a}','${b}','Only Alice and Bob');`);
for(const [user,count]of [[a,1],[b,1],[c,0]]){await db.exec(`set role authenticated;select set_config('test.member','yes',false);select set_config('request.jwt.claim.sub','${user}',false);`);assert.equal((await db.query('select * from class_direct_messages')).rows.length,count);const list=(await db.query("select * from classmates('class')")).rows;assert.equal(list.length,3);if(user===b)assert.equal(Number(list.find(x=>x.id===a).unread),1);if(user===c)assert.ok(list.every(x=>x.last_message===null&&Number(x.unread)===0));await assert.rejects(db.exec(`insert into class_direct_messages values(gen_random_uuid(),'class','${a}','${b}','spoof',now(),null)`),/permission denied/);await db.exec('reset role');}
await db.exec(`reset role;update class_direct_messages set read_at=now() where subspace_id='class' and sender_id='${a}' and recipient_id='${b}';set role authenticated;select set_config('test.member','yes',false);select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal(Number((await db.query(`select unread from classmates('class') where id='${a}'`)).rows[0].unread),0);
await db.exec("set role authenticated;select set_config('test.member','no',false)");assert.equal((await db.query("select * from classmates('class')")).rows.length,0);assert.equal((await db.query('select * from class_direct_messages')).rows.length,0);
}finally{await db.close();}});
