with expected(table_name,column_name,data_type) as (values
('profiles','id','uuid'),
('profiles','email','text'),
('profiles','name','text'),
('profiles','major','text'),
('profiles','interests','text'),
('profiles','avatar_url','text'),
('profiles','created_at','timestamp with time zone'),
('courses','id','text'),
('courses','code','text'),
('courses','title','text'),
('courses','term','text'),
('professors','id','text'),
('professors','name','text'),
('sections','id','text'),
('sections','course_id','text'),
('sections','professor_id','text'),
('sections','section_code','text'),
('sections','days','text'),
('sections','start_time','text'),
('sections','end_time','text'),
('sections','location','text'),
('enrollments','user_id','uuid'),
('enrollments','section_id','text'),
('spaces','id','text'),
('spaces','course_id','text'),
('subspaces','id','text'),
('subspaces','space_id','text'),
('subspaces','professor_id','text'),
('channels','id','text'),
('channels','subspace_id','text'),
('channels','name','text'),
('messages','id','text'),
('messages','channel_id','text'),
('messages','author_id','uuid'),
('messages','body','text'),
('messages','is_ai_response','boolean'),
('messages','meetup_id','text'),
('messages','created_at','timestamp with time zone'),
('meetups','id','text'),
('meetups','subspace_id','text'),
('meetups','creator_id','uuid'),
('meetups','title','text'),
('meetups','blurb','text'),
('meetups','location_name','text'),
('meetups','lat','double precision'),
('meetups','lng','double precision'),
('meetups','starts_at','timestamp with time zone'),
('meetups','created_at','timestamp with time zone'),
('meetup_attendees','meetup_id','text'),
('meetup_attendees','user_id','uuid'),
('meetup_attendees','joined_at','timestamp with time zone'),
('lecture_folders','id','text'),
('lecture_folders','subspace_id','text'),
('lecture_folders','date','timestamp with time zone'),
('lecture_folders','title','text'),
('notes','id','text'),
('notes','lecture_folder_id','text'),
('notes','uploader_id','uuid'),
('notes','file_name','text'),
('notes','file_url','text'),
('notes','mime_type','text'),
('notes','created_at','timestamp with time zone'),
('lecture_summaries','id','text'),
('lecture_summaries','lecture_folder_id','text'),
('lecture_summaries','content','text'),
('lecture_summaries','generated_at','timestamp with time zone'),
('course_schedules','id','text'),
('course_schedules','subspace_id','text'),
('course_schedules','raw_file_url','text'),
('course_schedules','uploaded_at','timestamp with time zone'),
('schedule_items','id','text'),
('schedule_items','schedule_id','text'),
('schedule_items','type','text'),
('schedule_items','title','text'),
('schedule_items','date','timestamp with time zone'),
('schedule_items','is_cumulative','boolean'),
('schedule_items','topics','text'),
('notification_settings','user_id','uuid'),
('notification_settings','event','text'),
('notification_settings','email_enabled','boolean'))
select (select count(*) from pg_tables where schemaname='public') as application_tables,
(select count(*) from pg_tables where schemaname='public' and not rowsecurity) as tables_without_rls,
(select count(*) from expected e left join information_schema.columns c
 on c.table_schema='public' and c.table_name=e.table_name and c.column_name=e.column_name
 where c.data_type is distinct from e.data_type) as missing_or_mistyped_fields,
(select count(*) from supabase_migrations.schema_migrations where version in ('202609050001','202609050002')) as applied_versions;
