import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {vector} from '@electric-sql/pglite/vector';
test('knowledge base isolates classes, deduplicates atomically, and fences stale workers',async()=>{
 const db=new PGlite({extensions:{vector}});
 try {
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema extensions;create schema storage;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
  create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,is_anonymous boolean default false,raw_user_meta_data jsonb default '{}');
  create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
  grant usage on schema public,auth,extensions to authenticated,anon,service_role;`);
  for(const name of ['202609050001_initial.sql','202609050002_domain.sql','202609050005_knowledge.sql','202609050006_knowledge_retrieval.sql','202609050007_knowledge_consistency.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
  const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';
  await db.exec(`insert into auth.users(id,email,email_confirmed_at)values('${a}','a@calpoly.edu',now()),('${b}','b@calpoly.edu',now());
  insert into courses(id,code,title,term)values('c','C','Course','Fall');insert into professors(id,name)values('p','P'),('q','Q');
  insert into sections(id,course_id,professor_id,section_code,days)values('s','c','p','01','M'),('t','c','q','02','T');
  insert into spaces(id,course_id)values('space','c');insert into subspaces(id,space_id,professor_id)values('class','space','p'),('other','space','q');
  insert into enrollments values('${a}','s'),('${b}','t');`);
  const u1='10000000-0000-0000-0000-000000000001',u2='10000000-0000-0000-0000-000000000002';
  const p={id:u1,subspace_id:'class',uploader_id:a,contribution_id:u1,file_name:'notes.txt',object_path:'path1',byte_size:12,description:'HW3',mime_type:'text/plain',sha256:'a'.repeat(64)};
  const attach=async data=>(await db.query('select kb_attach_upload($1::jsonb) id',[JSON.stringify(data)])).rows[0].id;
  const asset=await attach(p);assert.equal(await attach({...p,id:u2,object_path:'path2'}),asset);
  await assert.rejects(attach({...p,id:crypto.randomUUID(),uploader_id:b}),/Membership/);
  const job=(await db.query('select * from kb_claim_asset()')).rows[0];assert.equal(job.id,asset);
  assert.equal((await db.query('select * from kb_claim_asset()')).rows.length,0);
  const embedding=JSON.stringify([1,...Array(1535).fill(0)]);
  const chunks=[{ordinal:0,content:'A linked list consists of nodes.',locator:'Page 1',embedding}];
  assert.equal((await db.query('select kb_finish_asset($1,$2,$3::jsonb) ok',[asset,crypto.randomUUID(),JSON.stringify(chunks)])).rows[0].ok,false);
  await db.query('select kb_finish_asset($1,$2,$3::jsonb)',[asset,job.lease_token,JSON.stringify(chunks)]);
  await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${b}',false);`);
  assert.equal((await db.query('select * from kb_uploads')).rows.length,0);
  assert.equal((await db.query('select * from kb_chunks')).rows.length,0);
  assert.equal((await db.query("select * from kb_search('class',$1::extensions.vector,'linked',10)",[embedding])).rows.length,0);
  await assert.rejects(db.query('select kb_claim_asset()'),/permission denied/);
  await assert.rejects(db.query("insert into study_messages(id,subspace_id,channel,role,body,reply_to)values(gen_random_uuid(),'class','general','assistant','fake',gen_random_uuid())"),/permission denied/);
  await db.exec(`select set_config('request.jwt.claim.sub','${a}',false)`);
  assert.equal((await db.query("select * from kb_search('class',$1::extensions.vector,'linked',10)",[embedding])).rows.length,1);
  await db.exec('reset role');
  assert.equal((await db.query('select kb_remove_upload($1,$2) ok',[u1,b])).rows[0].ok,false);
  await db.query('select kb_remove_upload($1,$2)',[u1,a]);assert.equal((await db.query('select * from kb_chunks')).rows.length,1);
  await db.query('select kb_remove_upload($1,$2)',[u2,a]);assert.equal((await db.query('select * from kb_chunks')).rows.length,0);assert.equal((await db.query('select * from kb_garbage')).rows.length,2);
  assert.equal((await db.query('select kb_finish_asset($1,$2,$3::jsonb) ok',[asset,job.lease_token,JSON.stringify(chunks)])).rows[0].ok,false);
  const question=crypto.randomUUID();await db.query("insert into study_messages(id,subspace_id,channel,author_id,role,body,ai_status)values($1,'class','general',$2,'user','@AI hello','queued')",[question,a]);
  const q=(await db.query('select * from kb_claim_question()')).rows[0];
  const answer={body:'Answer',payload:{cards:[],sources:[]}};
  await db.query('select kb_finish_question($1,$2,$3)',[question,q.lease_token,answer]);
  await db.query('select kb_finish_question($1,$2,$3)',[question,q.lease_token,answer]);
  assert.equal((await db.query("select * from study_messages where role='assistant'")).rows.length,1);
 }finally{await db.close();}
});
