import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('notification saves respect column grants and isolate verified account preferences', async () => {
 const db = new PGlite();
 const owner = '00000000-0000-0000-0000-000000000001';
 const other = '00000000-0000-0000-0000-000000000002';
 const unverified = '00000000-0000-0000-0000-000000000003';
 try {
  await db.exec(`create role anon; create role authenticated; create schema auth;
   create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,is_anonymous boolean default false,raw_user_meta_data jsonb default '{}');
   create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
   grant usage on schema public,auth to anon,authenticated;
   grant execute on function auth.uid() to anon,authenticated;`);
  for (const file of ['202609050001_initial.sql', '202609050002_domain.sql']) {
   await db.exec(await readFile(new URL(`../supabase/migrations/${file}`, import.meta.url), 'utf8'));
  }
  await db.exec(`insert into auth.users(id,email,email_confirmed_at) values
   ('${owner}','owner@calpoly.edu',now()),('${other}','other@calpoly.edu',now()),('${unverified}','unverified@calpoly.edu',null);
   insert into notification_settings values ('${other}','MENTION',true);
   set role authenticated; select set_config('request.jwt.claim.sub','${owner}',false);`);

  // Reproduce the UPDATE assignments generated by a normal PostgREST upsert.
  await assert.rejects(db.exec(`insert into notification_settings values ('${owner}','MENTION',true)
   on conflict(user_id,event) do update set user_id=excluded.user_id,event=excluded.event,email_enabled=excluded.email_enabled`), /permission denied for table notification_settings/);

  async function save(enabled) {
   // PostgREST ignoreDuplicates generates DO NOTHING, requiring no key UPDATE.
   await db.exec(`insert into notification_settings values ('${owner}','MENTION',${enabled}),('${owner}','NEW_MESSAGE',${!enabled})
    on conflict(user_id,event) do nothing;
    update notification_settings set email_enabled=${enabled} where user_id='${owner}' and event in ('MENTION');
    update notification_settings set email_enabled=${!enabled} where user_id='${owner}' and event in ('NEW_MESSAGE');`);
  }
  for (const enabled of [true, false, true]) {
   await save(enabled);
   assert.deepEqual((await db.query('select event,email_enabled from notification_settings order by event')).rows,
    [{ event: 'MENTION', email_enabled: enabled }, { event: 'NEW_MESSAGE', email_enabled: !enabled }]);
  }
  await assert.rejects(db.exec(`update notification_settings set event='EXAM_REMINDER' where user_id='${owner}'`), /permission denied/);
  await assert.rejects(db.exec(`insert into notification_settings values ('${other}','EXAM_REMINDER',false) on conflict(user_id,event) do nothing`), /row-level security/);
  assert.equal((await db.query(`update notification_settings set email_enabled=false where user_id='${other}' returning *`)).rows.length, 0);
  await db.exec(`select set_config('request.jwt.claim.sub','${other}',false)`);
  assert.deepEqual((await db.query('select event,email_enabled from notification_settings')).rows, [{ event: 'MENTION', email_enabled: true }]);
  await db.exec(`select set_config('request.jwt.claim.sub','${unverified}',false)`);
  assert.equal((await db.query('select * from notification_settings')).rows.length, 0);
  await assert.rejects(db.exec(`insert into notification_settings values ('${unverified}','MENTION',true)`), /row-level security/);
  await db.exec('reset role; set role anon');
  await assert.rejects(db.query('select * from notification_settings'), /permission denied/);
 } finally { await db.close(); }
});
