'use client';
import {useState} from 'react';
import s from './profiles.module.css';
const options=[['01','The student card','Identity first. Your classes underneath.'],['02','The personal workspace','A quiet sidebar with one task at a time.'],['03','The essentials','A compact mobile profile with expandable sections.']];
const courses=[['AERO 1121','Aerospace Fundamentals','Isai Mauricio Villanueva','Mon · 12:00–2:50 PM'],['CSC 1001','Fundamentals of Computer Science','Anita Rathi','Tue & Thu · 9:00–10:20 AM']];
export default function ProfileConcepts(){
 const [choice,setChoice]=useState(0);const [section,setSection]=useState('Personal details');const [editing,setEditing]=useState(false);const [adding,setAdding]=useState(false);const [notice,setNotice]=useState('');
 function choose(i:number){setChoice(i);setSection('Personal details');setEditing(false);setAdding(false);setNotice('');}
 const details=<form className={s.form} onSubmit={e=>{e.preventDefault();setEditing(false);setNotice('Save interaction previewed. Your actual profile is unchanged.');}}><label>Display name<input defaultValue="Alex Morgan"/></label><label>Major<input defaultValue="Aerospace Engineering"/></label><label>About you<textarea defaultValue="Usually studying with a coffee. Always up for a good study group."/></label><label>Interests<input defaultValue="Space, design, hiking"/></label><button className={s.primary}>Save changes</button></form>;
 const notifications=<div className={s.preferences}><h3>Keep me in the loop</h3><p>Choose what reaches your inbox.</p>{['Meetup invitations','Meetup reminders','Class updates'].map(n=><label key={n}><span>{n}</span><input type="checkbox" defaultChecked role="switch"/></label>)}<p className={s.muted}>Sample preferences · preview only</p></div>;
 const classList=<div className={s.classes}>{courses.map(c=><article key={c[0]}><span className={s.courseIcon}>{c[0].split(' ')[0]}</span><div><strong>{c[0]}</strong><p>{c[1]}</p><small>{c[2]}<br/>{c[3]}</small></div><button aria-label={'Manage '+c[0]} onClick={()=>setNotice(c[0]+' selected. Course management would open here.')}>↗</button></article>)}</div>;
 const add=<button className={s.secondary} onClick={()=>setAdding(!adding)}>{adding?'Close course search':'+ Add a class'}</button>;
 const search=adding&&<form className={s.search} onSubmit={e=>{e.preventDefault();setNotice('Sample result: CSC 1001 · Anita Rathi. Enrollment is disabled in this preview.');}}><label>Find a course<input placeholder="Course code, e.g. CSC 1001" autoFocus/></label><button className={s.primary}>Search</button></form>;
 return <div className={s.page}>
  <div className={s.review}><div><span className={s.eyebrow}>STUDYCIRCLE / PROFILE DIRECTIONS</span><h1>Three ways to make it yours.</h1><p>Same features, different structure. Explore each direction.</p></div><span className={s.sample}>Interactive concepts · sample data</span></div>
  <nav className={s.options} aria-label="Profile concepts">{options.map((o,i)=><button key={o[0]} aria-pressed={choice===i} onClick={()=>choose(i)}><span>{o[0]}</span><strong>{o[1]}</strong><small>{o[2]}</small></button>)}</nav>
  <div className={`${s.app} ${choice===1?s.wide:''}`}>
   <header className={s.brand}><strong>✳ studycircle</strong><span>Cal Poly <span className={s.dot}>•</span> Fall 2026</span><span className={s.miniAvatar}>AM</span></header>
   {choice===0&&<main className={s.cardConcept}><div className={s.cover}><span>YOUR CORNER OF CAMPUS</span><span>✳</span></div><div className={s.identity}><div className={s.avatar}>AM</div><button className={s.secondary} onClick={()=>setEditing(!editing)}>{editing?'Close editor':'Edit profile'}</button></div><div className={s.bio}><h2>Alex Morgan</h2><p>Aerospace Engineering <span>· Cal Poly</span></p><p className={s.muted}>Usually studying with a coffee. Always up for a good study group.</p><div className={s.tags}><span>Space</span><span>Design</span><span>Hiking</span></div></div>{editing&&details}<div className={s.sectionHead}><div><span className={s.eyebrow}>FALL 2026</span><h3>My classes <small>02</small></h3></div>{add}</div>{search}{classList}<div className={s.accountRow}><button onClick={()=>setSection(section==='Notifications'?'Personal details':'Notifications')}>Notifications <span>→</span></button><button onClick={()=>setNotice('Sign out is disabled in this preview.')}>Sign out ↗</button></div>{section==='Notifications'&&notifications}</main>}
   {choice===1&&<div className={s.workspace}><aside className={s.sidebar}><span className={s.eyebrow}>MY ACCOUNT</span><div className={s.avatar}>AM</div><h2>Alex Morgan</h2><p>Aerospace Engineering</p><nav aria-label="Account sections">{['Personal details','My classes','Notifications'].map((n,i)=><button key={n} aria-current={section===n?'page':undefined} onClick={()=>{setSection(n);setAdding(false);setNotice('');}}><span>{['◉','▦','◌'][i]}</span>{n}<span>→</span></button>)}</nav><div className={s.sidebarFoot}><small>alex.morgan@calpoly.edu</small><button onClick={()=>setNotice('Sign out is disabled in this preview.')}>Sign out ↗</button></div></aside><main className={s.workspaceContent}><span className={s.eyebrow}>PROFILE / {section.toUpperCase()}</span><h2>{section}</h2><p className={s.muted}>{section==='Personal details'?'A little about you, for the people you study with.':section==='My classes'?'Your courses and professors, all in one place.':'Helpful updates, on your terms.'}</p>{section==='Personal details'?details:section==='My classes'?<><div className={s.sectionHead}><h3>Fall 2026</h3>{add}</div>{search}{classList}</>:notifications}</main></div>}
   {choice===2&&<main className={s.essential}><span className={s.eyebrow}>MY PROFILE</span><div className={s.essentialIdentity}><div className={s.avatar}>AM</div><div><h2>Alex Morgan</h2><p>Aerospace Engineering</p><small>alex.morgan@calpoly.edu</small></div></div><div className={s.summary}><span><strong>2</strong> classes this term</span><span>Cal Poly · Fall 2026</span></div><div className={s.accordions}><details open><summary><span><strong>My classes</strong><small>Your courses and professors</small></span><span>02 ＋</span></summary><div className={s.accordionBody}>{classList}{add}{search}</div></details><details><summary><span><strong>Personal details</strong><small>Name, major, and interests</small></span><span>＋</span></summary><div className={s.accordionBody}>{details}</div></details><details><summary><span><strong>Notifications</strong><small>Choose the updates you receive</small></span><span>＋</span></summary><div className={s.accordionBody}>{notifications}</div></details></div><button className={s.signout} onClick={()=>setNotice('Sign out is disabled in this preview.')}>Sign out</button></main>}
   {notice&&<p className={s.notice} role="status">{notice}</p>}
   <footer className={s.bottom}><span>◷<small>Meetups</small></span><span>◌<small>Chat</small></span><span>▱<small>Files</small></span><span className={s.current}>◉<small>Profile</small></span></footer>
  </div><p className={s.caption}>{choice===0?'01 — A profile that feels like a person. Editing and preferences stay secondary.':choice===1?'02 — Clear separation. Each section gets its own focused space.':'03 — Everything within reach. Expand what you need and keep the rest tucked away.'}</p>
 </div>;
}
