'use client';
/* eslint-disable @next/next/no-img-element -- User-provided profile photos use native loading and an initials fallback. */
import Link from 'next/link';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useFillViewport} from '@/lib/use-fill-viewport';
import css from './Classmates.module.css';
type Member={id:string;name:string|null;major:string|null;avatar_url:string|null;unread:number;last_message:string|null;last_at:string|null};
type Message={id:string;sender_id:string;recipient_id:string;body:string;created_at:string;read_at:string|null};
async function api<T>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,{cache:'no-store',...options});const d=await r.json();if(!r.ok)throw new Error(d.error||'Please try again.');return d;}
function Avatar({member}:{member:Member}){return <span className={css.avatar}>{member.avatar_url?<img src={member.avatar_url} alt="" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.display='none';}}/>:null}<span>{(member.name||'Classmate').split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase()}</span></span>;}
function Conversation({member,subspace,userId,onBack}:{member:Member;subspace:string;userId:string;onBack:()=>void}){
 const [messages,setMessages]=useState<Message[]>([]),[loaded,setLoaded]=useState(false),[hasMore,setHasMore]=useState(false),[loadingOlder,setLoadingOlder]=useState(false),[draft,setDraft]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('');
 const log=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),retry=useRef<string|null>(null),nearBottom=useRef(true),initialized=useRef(false);
 const url=`/api/classmates?class=${encodeURIComponent(subspace)}&peer=${member.id}`;
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;async function poll(){try{const d=await api<{messages:Message[];hasMore:boolean}>(url,{signal:c.signal});if(c.signal.aborted)return;setLoaded(true);setError('');if(!initialized.current){setHasMore(d.hasMore);initialized.current=true;}setMessages(old=>{const map=new Map(old.map(m=>[m.id,m]));d.messages.forEach(m=>map.set(m.id,m));return [...map.values()].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));});if(!document.hidden){const ids=d.messages.filter(m=>m.recipient_id===userId&&!m.read_at).map(m=>m.id);if(ids.length)await api(url,{method:'PATCH',signal:c.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({peer:member.id,ids})});}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Messages could not be loaded.');}if(!c.signal.aborted)timer=setTimeout(poll,3000);}void poll();return()=>{c.abort();clearTimeout(timer);};},[url,member.id,userId]);
 useEffect(()=>{if(nearBottom.current&&log.current)log.current.scrollTop=log.current.scrollHeight;},[messages]);
 useEffect(()=>{if(input.current){input.current.style.height='auto';input.current.style.height=Math.min(input.current.scrollHeight,130)+'px';}},[draft]);
 async function older(){if(!messages.length)return;setLoadingOlder(true);try{const first=messages[0],d=await api<{messages:Message[];hasMore:boolean}>(url+`&before=${encodeURIComponent(first.created_at)}&cursor=${first.id}`);const el=log.current,previous=el?.scrollHeight||0;nearBottom.current=false;setMessages(old=>[...d.messages.filter(m=>!old.some(o=>o.id===m.id)),...old]);setHasMore(d.hasMore);const ids=d.messages.filter(m=>m.recipient_id===userId&&!m.read_at).map(m=>m.id);if(ids.length)void api(url,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({peer:member.id,ids})}).catch(()=>{});requestAnimationFrame(()=>{if(el)el.scrollTop+=el.scrollHeight-previous;});}catch(e){setError(e instanceof Error?e.message:'Could not load earlier messages.');}finally{setLoadingOlder(false);}}
 async function send(e:FormEvent){e.preventDefault();if(!draft.trim()||pending)return;setPending(true);setError('');retry.current||=crypto.randomUUID();try{const result=await api<{message:Message}>(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:retry.current,peer:member.id,body:draft.trim()})});nearBottom.current=true;setMessages(old=>old.some(m=>m.id===result.message.id)?old:[...old,result.message]);setDraft('');retry.current=null;}catch(e){setError(e instanceof Error?e.message:'Message could not be sent.');}finally{setPending(false);input.current?.focus();}}
 return <section className={css.conversation} aria-label={'Conversation with '+member.name}><header className={css.conversationHeader}><button className={css.back} onClick={onBack} aria-label="Back to classmates">‹</button><Avatar member={member}/><div><h2>{member.name||'Classmate'}</h2><p>Private conversation</p></div></header>
 <div className={css.log} ref={log} onScroll={()=>{const el=log.current;if(el)nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<70;}} role="log" aria-label="Direct messages" aria-live="polite">
 {hasMore&&<button className={css.older} disabled={loadingOlder} onClick={older}>{loadingOlder?'Loading…':'Earlier messages'}</button>}
 {!loaded?<p className={css.empty}>Loading conversation…</p>:!messages.length?<div className={css.empty}><h3>Say hello to {member.name?.split(' ')[0]||'your classmate'}</h3><p>Ask a question, share an idea, or plan a study session.</p></div>:messages.map(m=><div className={css.message} data-own={m.sender_id===userId} key={m.id}><p>{m.body}</p><small>{new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>)}
 </div><form onSubmit={send} className={css.composer}>{error&&<p role="alert" className={css.error}>{error}</p>}<div><textarea ref={input} rows={1} maxLength={2000} aria-label={'Message '+member.name} placeholder="Write a message…" value={draft} disabled={pending} onChange={e=>{setDraft(e.target.value);retry.current=null;}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><button aria-label="Send message" disabled={pending||!draft.trim()}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M12 20V4m-6 6 6-6 6 6"/></svg></button></div></form></section>;
}
export default function Classmates({subspace,userId,aiHref}:{subspace:string;userId:string;aiHref:string}){
 const {sectionRef,height}=useFillViewport<HTMLElement>();const [members,setMembers]=useState<Member[]|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<Member|null>(null);
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;async function load(){try{const d=await api<{members:Member[]}>(`/api/classmates?class=${encodeURIComponent(subspace)}`,{signal:c.signal});if(!c.signal.aborted){setMembers(d.members);setError('');}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Classmates could not be loaded.');}if(!c.signal.aborted)timer=setTimeout(load,5000);}void load();return()=>{c.abort();clearTimeout(timer);};},[subspace]);
 const visible=(members||[]).filter(m=>(m.name||'Classmate').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.unread>0)-Number(a.unread>0)||(b.last_at||'').localeCompare(a.last_at||'')||(a.name||'').localeCompare(b.name||''));
 return <section id="classmates-surface" ref={sectionRef} style={height===null?undefined:{height}} className={css.surface} data-conversation={!!selected}><aside className={css.directory}><header><h1>Classmates</h1><p>{members?`${members.length} in your class`:'Your class, together'}</p></header><input className={css.search} aria-label="Find a classmate" placeholder="Find a classmate…" value={query} onChange={e=>setQuery(e.target.value)}/><div className={css.members}><Link href={aiHref} className={css.ai}><span className={css.aiAvatar}>AI</span><div><strong>Circle AI</strong><p>Your private study assistant</p></div><span aria-hidden="true">›</span></Link><p className={css.label}>YOUR CLASS</p>{error&&<p className={css.error} role="alert">{error}</p>}{!members&&!error&&<p className={css.empty}>Loading classmates…</p>}{members&&!visible.length&&<p className={css.empty}>No classmates match that name.</p>}{visible.map(m=><button className={css.person} key={m.id} disabled={m.id===userId} aria-current={selected?.id===m.id?'true':undefined} onClick={()=>setSelected(m)}><Avatar member={m}/><div><strong>{m.name||'Classmate'}{m.id===userId&&<small> You</small>}</strong><p>{m.last_message||m.major||'Classmate'}</p></div>{m.unread>0&&<span className={css.unread} aria-label={`${m.unread} unread messages`}>{m.unread}</span>}</button>)}</div></aside>{selected?<Conversation key={selected.id} member={selected} userId={userId} subspace={subspace} onBack={()=>setSelected(null)}/>:<div className={css.welcome}><span className={css.welcomeSymbol}>“</span><h2>A conversation starts here</h2><p>Choose a classmate to send a private message,<br/>or study with Circle AI.</p></div>}</section>;
}
